export const LOAD_TEAMS = 'LOAD_TEAMS'
export const LOAD_TRADE_TEAM_DATA = 'LOAD_TRADE_TEAM_DATA'
export const REMOVE_ALL_TRADE_TEAMS = 'REMOVE_ALL_TRADE_TEAMS'
export const ADD_PLAYER_TO_TRADE = 'ADD_PLAYER_TO_TRADE'
export const ADD_DRAFTPICK_TO_TRADE = 'ADD_DRAFTPICK_TO_TRADE'
export const ADD_ASSET_TO_TRADE = 'ADD_ASSET_TO_TRADE'
export const REMOVE_TRADE_ASSET = 'REMOVE_TRADE_ASSET'

export const WAIVE_PLAYER = 'WAIVE_PLAYER'
export const CHANGE_DATE = 'CHANGE_DATE'
export const SET_SEASON = 'SET_SEASON'
export const RENOUNCE_CAP_HOLD = 'RENOUNCE_CAP_HOLD'
export const LOAD_FREE_AGENTS = 'LOAD_FREE_AGENTS'

export const OPT_OUT_PLAYER_CONTRACT = 'OPT_OUT_PLAYER_CONTRACT'
export const OPT_IN_PLAYER_CONTRACT = 'OPT_IN_PLAYER_CONTRACT'

export const PICK_UP_TEAM_OPTION = 'PICK_UP_TEAM_OPTION'
export const DECLINE_TEAM_OPTION = 'DECLINE_TEAM_OPTION'

export const CREATE_NEW_CONTRACT = 'CREATE_NEW_CONTRACT'
